
import waftools.process_resources as res

def build(bld):

    res.gen_resource_deps(bld,
                          map_node=bld.path.find_node('src/resource_map.json'),
                          pack_node=bld.path.parent.get_bld().make_node('app_resources.pbpack'),
                          id_header_node=bld.path.parent.get_bld().make_node('src/resource_ids.auto.h'),
                          resource_header_path="pebble_os.h")
            

